version: "3"
services:
  db-users:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: creative-hub-users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  mail-server:
    image: maildev/maildev
    ports:
      - "1080:80"
  users-microservice:
    build: .
    image: creative-hub/users-microservice:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-users:5432/creative-hub-users
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db-users
      - mail-server
