apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: db-users
  name: db-users
spec:
  ports:
    - name: jdbc
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: db-users
