apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mail-server
  name: mail-server
spec:
  type: LoadBalancer
  ports:
    - name: ui
      port: 1080
      targetPort: 80
  selector:
    io.kompose.service: mail-server
