apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mail-server
  name: mail-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mail-server
  strategy: { }
  template:
    metadata:
      labels:
        io.kompose.service: mail-server
    spec:
      containers:
        - image: maildev/maildev
          name: mail-server
          ports:
            - containerPort: 80
          resources: { }
      restartPolicy: Always
