apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: users-microservice
  name: users-microservice
spec:
  type: LoadBalancer
  ports:
    - name: api
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: users-microservice
