apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-server
  labels:
    app: mail-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-server
  template:
    metadata:
      labels:
        app: mail-server
    spec:
      containers:
        - name: mail-server
          image: maildev/maildev
          ports:
            - containerPort: 1080
            - containerPort: 25

---
apiVersion: v1
kind: Service
metadata:
  name: mail-server
spec:
  selector:
    app: mail-server
  ports:
    - name: smtp
      protocol: TCP
      port: 25
      targetPort: 25
    - name: http
      protocol: TCP
      port: 1080
      targetPort: 1080