apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: microservice-users
  name: microservice-users
spec:
  ports:
    - name: api
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: microservice-users
