apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: microservice-users
  name: microservice-users
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: microservice-users
  strategy: { }
  template:
    metadata:
      labels:
        io.kompose.service: microservice-users
    spec:
      containers:
        - env:
            - name: RABBITMQ_HOST
              value: $RABBITMQ_HOST
            - name: RABBITMQ_PORT
              value: $RABBITMQ_PORT
            - name: RABBITMQ_USERNAME
              value: $RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              value: $RABBITMQ_PASSWORD
            - name: API_GATEWAY_URL
              value: $GATEWAY_URL
            - name: DB_HOST
              value: db-users
            - name: DB_NAME
              value: creative-hub-users
            - name: DB_PASSWORD
              value: postgres
            - name: DB_USERNAME
              value: postgres
            - name: JWT_SECRET
              value: 7638792F423F4528472B4B6250655368566D597133743677397A24432646294A
            - name: MAIL_HOST
              value: mail-server
            - name: MAIL_PORT
              value: "1025"
          image: ghcr.io/creative-hub-taass/microservice-users:latest
          name: microservice-users
          ports:
            - containerPort: 8080
          resources: { }
      restartPolicy: Always
