
#PersistentVolumeClaim è un volume reso disponibile a postgres per memorizzare i dati
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim # name of PVC essential for identifying the storage data
  labels:
    app: postgres
    tier: database
spec:
  accessModes:
    - ReadWriteOnce #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 1Gi #This will tell kubernetes about the amount of space we are trying to claim.
---
#Servizio simile a un load balancer.
#Definizione del servizio che crea un pod del database utente accessibile all'interno del cluster
#L'accesso solamente da parte dei componenti all'interno del cluster è garantito dalla mancanza del campo kind
#Per default, la mancanza del campo field, assegna ad essa ClusterIP che rende il servizio accessibile solo ai pod del cluster
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
    tier: database
---
#Deployment crea ed esegue i containers e li mantiene in esecuzione
#Contiene il campo volumes che definisce un volume di memorizzazione chiamato storage
#Storage riferisce al PersistentVolumeClaim definito in precedenza
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    tier: database
spec:  # Postgres Pod Should contain same labels
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:  # Must match 'Service' and 'Deployment' selectors
        app: postgres
        tier: database
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: creative-hub-users
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgres
              name: postgres-persistance-storage
      volumes:
        - name: postgres-persistance-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim